### ISSUE TITLE
Add a contributing guide for developers.

### ISSUE THREAD

**Issue by ShyamPraveenSingh** [ShyamPraveenSingh/HTML-Contact_Form#5]
## Add a contributing guide for developers.

Here is an example [CONTRIBUTING.md](https://github.com/ShyamPraveenSingh/Weather-Forecast-App/blob/master/CONTRIBUTING.mdl)

**Comment by danger-ahead** [comment]
Hi, I can help. Please assign me

**Comment by ShyamPraveenSingh** [comment]
Sure! Go ahead.
